In [1]:
import numpy as np
import pandas as pd

from physipy import m, s, DimensionError

from physipandas import QuantityDtype, QuantityArray

# Creation of series

In [2]:
print("CONSTRUCTING a")
a = pd.Series(QuantityArray(np.arange(10)*m))
print(a.index, type(a.values), type(a.values[0]), len(a.values))

a = pd.Series(QuantityArray(np.arange(10)*m), dtype="physipy[m]")
print(a.index, type(a.values), type(a.values[0]), len(a.values))

a = pd.Series(QuantityArray(np.arange(10)*m), dtype=QuantityDtype(m))
print(a.index, type(a.values), type(a.values[0]), len(a.values))


print()
print("CONSTRUCTING b")
b = pd.Series(np.arange(10)*m, 
              dtype="physipy[m]")
print(b.index, type(b.values), type(b.values[0]), len(b.values))

#print()
#print("CONSTRUCTING c")
#c = pd.Series(np.arange(10)*m, 
#              dtype=QuantityDtype(m))

print()
print(a.dtype, b.dtype, a.dtype == b.dtype)
print(a.values == b.values)
#print(a.values == c.values)
print(type(a) == type(b))
#print(type(a) == type(c))
print(type(a.values) == type(b.values))
#print(type(a.values) == type(c.values))
print(len(a), len(b))
#print(len(a), len(c))


try:
    d = pd.Series(np.arange(10)*m,
              dtype=QuantityDtype(s))
except Exception as e:
    print('OK', str(e))
    
try:
    f = pd.Series(np.arange(10), dtype=QuantityDtype(m))
except Exception as e:
    print('OK', str(e))
    
try:
    f = pd.Series(np.arange(10)*m, dtype=QuantityDtype(1))
except Exception as e:
    print('OK', str(e))


CONSTRUCTING a
ENTERING QARRAY with [0 1 2 3 4 5 6 7 8 9] m None False
QARRAY : init with [0 1 2 3 4 5 6 7 8 9] m of type <class 'physipy.quantity.quantity.Quantity'>
data is set to [0 1 2 3 4 5 6 7 8 9] m with len 10 10
len values 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
dtype is then set to  physipy[m]
Length of QuantityArray 10
Length of QuantityArray 10
RangeIndex(start=0, stop=10, step=1) <class 'physipandas.extension.QuantityArray'> <class 'physipy.quantity.quantity.Quantity'> 10
ENTERING QARRAY with [0 1 2 3 4 5 6 7 8 9] m None False
QARRAY : init with [0 1 2 3 4 5 6 7 8 9] m of type <class 'physipy.quantity.quantity.Quantity'>
data is set to [0 1 2 3 4 5 6 7 8 9] m with len 10 10
len values 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
dtype is then set to  physipy[m]
QDTYPE : construct_from_string with physipy[m]
QDTYPE : construct_from

## Creation of QArray

In [14]:
qarr = np.arange(10)*m

pdqarr = QuantityArray(qarr)
e = pd.Series(QuantityArray.from_1darray_quantity(np.arange(10)*m))

QARRAY : init with [0 1 2 3 4 5 6 7 8 9] m of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [0 1 2 3 4 5 6 7 8 9] m with len 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m


<QuantityArray>
[0 m, 1 m, 2 m, 3 m, 4 m, 5 m, 6 m, 7 m, 8 m, 9 m]
Length: 10, dtype: physipy[m]

# This works

# Checking the QuantityArray constructions

In [14]:
import physipy
from physipy import m, s, DimensionError

import numpy as np
import pandas as pd

from physipandas import QuantityDtype, QuantityArray

a = pd.Series(QuantityArray(np.arange(10)*m))
b = pd.Series(QuantityArray(np.arange(10)*m))
c = pd.Series(QuantityArray(np.arange(10)*s))

print(a, b, c)

print(len(a), len(b), len(c))
print(a.shape, b.shape, c.shape)
print(type(a))
print(a.dtype)
print(type(a[0]))
print(a[0].dtype)

QARRAY : init with [0 1 2 3 4 5 6 7 8 9] m of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [0 1 2 3 4 5 6 7 8 9] m with len 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
QARRAY : init with [0 1 2 3 4 5 6 7 8 9] m of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [0 1 2 3 4 5 6 7 8 9] m with len 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
QARRAY : init with [0 1 2 3 4 5 6 7 8 9] s of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [0 1 2 3 4 5 6 7 8 9] s with len 10
QDTYPE : new with 1 s of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[s] with .unit 1 s
0   0
1   1
2   2
3   3
4   4
5   5
6   6
7   7
8   8
9   9
dtype: physipy[m] 0   0
1   1
2   2
3   3
4   4
5   5
6   6
7   7
8   8
9   9
dtype: physipy[m] 0   0
1   1
2

In [15]:
try:
    a+1
except DimensionError:
    print("OK")

print(a+1*m)
print(a+np.arange(10)*m)
print(a+a)
print(2*a)
print(a*2)
print(a**2)
print(a[0])
print(a[0:2])
print(a.iloc[0:3])

OK
QARRAY : init with [ 1  2  3  4  5  6  7  8  9 10] m of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [ 1  2  3  4  5  6  7  8  9 10] m with len 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
dtype: physipy[m]
QARRAY : init with [ 0  2  4  6  8 10 12 14 16 18] m of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [ 0  2  4  6  8 10 12 14 16 18] m with len 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
0    0
1    2
2    4
3    6
4    8
5   10
6   12
7   14
8   16
9   18
dtype: physipy[m]
QARRAY : init with [ 0  2  4  6  8 10 12 14 16 18] m of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [ 0  2  4  6  8 10 12 14 16 18] m with len 10
QDTYPE : new with 1 m of type <class 'phys

# Dataframes

In [16]:
df = pd.DataFrame({"a":a, "b":b, "c":c})

res = 2*df["a"]
df["d"] = res

df["e"] = df["d"]*2
df["g"] = df["e"]*df["a"]/df["c"]**2

QARRAY : init with [ 0  2  4  6  8 10 12 14 16 18] m of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [ 0  2  4  6  8 10 12 14 16 18] m with len 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
into copy
data is  [ 0  2  4  6  8 10 12 14 16 18] m
dtype is physipy[m]
QARRAY : init with [ 0  2  4  6  8 10 12 14 16 18] m of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [ 0  2  4  6  8 10 12 14 16 18] m with len 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
QARRAY : init with [ 0  4  8 12 16 20 24 28 32 36] m of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [ 0  4  8 12 16 20 24 28 32 36] m with len 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
into copy
data is  [ 0  4  8 12 16 2

/Users/mocquin/MYLIB10/MODULES/physipy/physipy/quantity/quantity.py:189: RuntimeWarning: invalid value encountered in true_divide
  return type(self)(self.value / y.value,


In [23]:
print(df["g"].physipy.dimension)
df["g"].physipy._SI_unitary_quantity

L**2/T**2


<Quantity : 1 m**2/s**2, symbol=m**2/s**2>

In [19]:
df.physipy.to_base_units()

AttributeError: 'PhysipySeriesAccessor' object has no attribute 'to_base_units'

# This works : should fail and does

In [9]:
try:
    a=pd.Series(np.arange(10)*m,
            dtype=QuantityDtype(s))
    print("--")
    print(type(a[0]))
    print((a[0]))
except DimensionError as e:
    print(e)
    print("OK : trying to set second to m")

New dtype with :1 s
unit is 1 s <class 'physipy.quantity.quantity.Quantity'>
Constructing QuantityArray with  [<Quantity : [0 1 2 3 4 5 6 7 8 9] m>] dtype= physipy[s]
New dtype with :1 
unit is 1 <class 'physipy.quantity.quantity.Quantity'>
--
in getitiem
<class 'physipy.quantity.quantity.Quantity'>
in getitiem
[0 1 2 3 4 5 6 7 8 9]


# This fails : should be 0 m

In [10]:
a = pd.Series(np.arange(10)*m,
            dtype=QuantityDtype())
print(a[0])

New dtype with :None
unit is 1 <class 'physipy.quantity.quantity.Quantity'>
Constructing QuantityArray with  [<Quantity : [0 1 2 3 4 5 6 7 8 9] m>] dtype= physipy[]
New dtype with :1 
unit is 1 <class 'physipy.quantity.quantity.Quantity'>
in getitiem
[0 1 2 3 4 5 6 7 8 9]


# Should this work ?

In [11]:
a=pd.Series(np.arange(10), 
            dtype=QuantityDtype(s))
print(type(a[0]))
print(a[0])
print(a.values.dimension)

New dtype with :1 s
unit is 1 s <class 'physipy.quantity.quantity.Quantity'>
Constructing QuantityArray with  [0 1 2 3 4 5 6 7 8 9] dtype= physipy[s]
New dtype with :1 
unit is 1 <class 'physipy.quantity.quantity.Quantity'>
in getitiem
<class 'physipy.quantity.quantity.Quantity'>
in getitiem
0
no-dimension


In [12]:
a=pd.Series(np.arange(10)*m)
print(type(a[0]))
print((a[0]))
print(a)

<class 'physipy.quantity.quantity.Quantity'>
[0 1 2 3 4 5 6 7 8 9] m
0    [0 m, 1 m, 2 m, 3 m, 4 m, 5 m, 6 m, 7 m, 8 m, ...
dtype: object


In [13]:
s = pd.Series(["a", "b", "c", "a"], dtype="category")
s

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): ['a', 'b', 'c']

In [16]:
pd.Series(["a", "b", "c", "a"])

0    a
1    b
2    c
3    a
dtype: object

In [11]:
from pandas.api.extensions import register_extension_dtype

register_extension_dtype?

Signature: register_extension_dtype(cls: Type[pandas.core.dtypes.base.ExtensionDtype]) -> Type[pandas.core.dtypes.base.ExtensionDtype]
Docstring:
Register an ExtensionType with pandas as class decorator.

.. versionadded:: 0.24.0

This enables operations like ``.astype(name)`` for the name
of the ExtensionDtype.

Returns
-------
callable
    A class decorator.

Examples
--------
>>> from pandas.api.extensions import register_extension_dtype
>>> from pandas.api.extensions import ExtensionDtype
>>> @register_extension_dtype
... class MyExtensionDtype(ExtensionDtype):
...     name = "myextension"
File:      /opt/anaconda3/lib/python3.8/site-packages/pandas/core/dtypes/base.py
Type:      function
