In [30]:
import numpy as np
import pandas as pd

from physipy import m, s, DimensionError, K

from physipandas import QuantityDtype, QuantityArray

arr = np.linspace(260, 400)

df = pd.DataFrame({
    "A":arr,
})

# https://github.com/pandas-dev/pandas/blob/196b28a899b2469fef34dc4ee61342053c7b6916/pandas/core/internals/construction.py#L586

#df = pd.DataFrame({
#    "TCN":arr*K
#})
df

A
0   260.000000
1   262.857143
2   265.714286
3   268.571429
4   271.428571
5   274.285714
6   277.142857
7   280.000000
8   282.857143
9   285.714286
10  288.571429
11  291.428571
12  294.285714
13  297.142857
14  300.000000
15  302.857143
16  305.714286
17  308.571429
18  311.428571
19  314.285714
20  317.142857
21  320.000000
22  322.857143
23  325.714286
24  328.571429
25  331.428571
26  334.285714
27  337.142857
28  340.000000
29  342.857143
30  345.714286
31  348.571429
32  351.428571
33  354.285714
34  357.142857
35  360.000000
36  362.857143
37  365.714286
38  368.571429
39  371.428571
40  374.285714
41  377.142857
42  380.000000
43  382.857143
44  385.714286
45  388.571429
46  391.428571
47  394.285714
48  397.142857
49  400.000000

In [22]:

from pandas.core.dtypes.generic import (
    ABCDataFrame,
    ABCSeries,
)
from pandas.core.dtypes.common import (
#    is_1d_only_ea_dtype,
    is_datetime64tz_dtype,
    is_datetime_or_timedelta_dtype,
    is_dtype_equal,
    is_extension_array_dtype,
    is_integer_dtype,
    is_list_like,
    is_named_tuple,
    is_object_dtype,
)
def _extract_index(data):
    """
    Try to infer an Index from the passed data, raise ValueError on failure.
    """
    index = None
    print("len(data)", len(data))
    if len(data) == 0:
        index = Index([])
    elif len(data) > 0:
        raw_lengths = []
        indexes: list[list[Hashable] | Index] = []

        have_raw_arrays = False
        have_series = False
        have_dicts = False

        for val in data:
            print("val:", val)
            if isinstance(val, ABCSeries):
                print("val isinstance ABCSeries")
                have_series = True
                indexes.append(val.index)
            elif isinstance(val, dict):
                print("val isinstance dict")
                have_dicts = True
                indexes.append(list(val.keys()))
            elif is_list_like(val) and getattr(val, "ndim", 1) == 1:
                print("val islistlike")
                have_raw_arrays = True
                raw_lengths.append(len(val))

        if not indexes and not raw_lengths:
            raise ValueError("If using all scalar values, you must pass an index")

        if have_series:
            index = union_indexes(indexes)
        elif have_dicts:
            index = union_indexes(indexes, sort=False)

        if have_raw_arrays:
            lengths = list(set(raw_lengths))
            if len(lengths) > 1:
                raise ValueError("All arrays must be of the same length")

            if have_dicts:
                raise ValueError(
                    "Mixing dicts with non-Series may lead to ambiguous ordering."
                )

            if have_series:
                assert index is not None  # for mypy
                if lengths[0] != len(index):
                    msg = (
                        f"array length {lengths[0]} does not match index "
                        f"length {len(index)}"
                    )
                    raise ValueError(msg)
            else:
                index = ibase.default_index(lengths[0])

    # error: Argument 1 to "ensure_index" has incompatible type "Optional[Index]";
    # expected "Union[Union[Union[ExtensionArray, ndarray], Index, Series],
    # Sequence[Any]]"
    return ensure_index(index)  # type: ignore[arg-type]

In [28]:
pd.core.dtypes.common.is_list_like?

Docstring:
Check if the object is list-like.

Objects that are considered list-like are for example Python
lists, tuples, sets, NumPy arrays, and Pandas Series.

Strings and datetime objects, however, are not considered list-like.

Parameters
----------
obj : object
    Object to check.
allow_sets : bool, default True
    If this parameter is False, sets will not be considered list-like.

    .. versionadded:: 0.24.0

Returns
-------
bool
    Whether `obj` has list-like properties.

Examples
--------
>>> is_list_like([1, 2, 3])
True
>>> is_list_like({1, 2, 3})
True
>>> is_list_like(datetime(2017, 1, 1))
False
>>> is_list_like("foo")
False
>>> is_list_like(1)
False
>>> is_list_like(np.array([2]))
True
>>> is_list_like(np.array(2))
False
Type:      builtin_function_or_method


# Creation of series

In [10]:
print("CONSTRUCTING a")
a = pd.Series(QuantityArray(np.arange(10)*m))
print(a.index, type(a.values), a.values.shape, type(a.values[0]), len(a.values))

a = pd.Series(QuantityArray(np.arange(10)*m), dtype="physipy[m]")
print(a.index, type(a.values), a.values.shape, type(a.values[0]), len(a.values))

a = pd.Series(QuantityArray(np.arange(10)*m), dtype=QuantityDtype(m))
print(a.index, type(a.values), a.values.shape, type(a.values[0]), len(a.values))




print()
print((QuantityArray(np.arange(10)*m)).size)
print((np.arange(10)*m).size)

print("CONSTRUCTING b")
b = pd.Series(np.arange(10)*m, dtype="physipy[m]")
print(b.index, type(b.values), b.values.shape, type(b.values[0]), len(b.values))


#bb = b.reset_index()
#print()
#print("CONSTRUCTING c")
#c = pd.Series(np.arange(10)*m, 
#              dtype=QuantityDtype(m))

print()
print(a.dtype, b.dtype, a.dtype == b.dtype)
print(a.values == b.values)
#print(a.values == c.values)
print(type(a) == type(b))
#print(type(a) == type(c))
print(type(a.values) == type(b.values))
#print(type(a.values) == type(c.values))
print(len(a), len(b))
#print(len(a), len(c))



CONSTRUCTING a
ENTERING QARRAY with [0 1 2 3 4 5 6 7 8 9] m None False
QARRAY : init with [0 1 2 3 4 5 6 7 8 9] m of type <class 'physipy.quantity.quantity.Quantity'>
data is set to [0 1 2 3 4 5 6 7 8 9] m with len 10 10 <class 'physipy.quantity.quantity.Quantity'>
len values 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
dtype is then set to  physipy[m]
Length of QuantityArray 10
Length of QuantityArray 10
Length of QuantityArray 10
RangeIndex(start=0, stop=10, step=1) <class 'physipandas.extension.QuantityArray'> (10,) <class 'physipy.quantity.quantity.Quantity'> 10
ENTERING QARRAY with [0 1 2 3 4 5 6 7 8 9] m None False
QARRAY : init with [0 1 2 3 4 5 6 7 8 9] m of type <class 'physipy.quantity.quantity.Quantity'>
data is set to [0 1 2 3 4 5 6 7 8 9] m with len 10 10 <class 'physipy.quantity.quantity.Quantity'>
len values 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physip

In [3]:
a = pd.Series([1, 2, 3]*m, dtype='physipy[m]')
print(a)
print(a.values)

QDTYPE : construct_from_string with physipy[m]
QDTYPE : construct_from_string, actual unit found 1 m . Returning QuantityDtype(1 m)
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
calling qARRY with ()
trying from sequence  [<Quantity : [1 2 3] m, symbol=UndefinedSymbol*m>] 1 physipy[m]
ENTERING QARRAY with [[1 2 3]] m physipy[m] False
QARRAY : init with [[1 2 3]] m of type <class 'physipy.quantity.quantity.Quantity'>
data is set to [[1 2 3]] m with len 1 3 <class 'physipy.quantity.quantity.Quantity'>
len values 1
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
dtype is then set to  physipy[m]
Length of QuantityArray 1
in array None
0   [1 2 3]
dtype: physipy[m]
Length of QuantityArray 1
Length of QuantityArray 1
<QuantityArray>
[[1 2 3] m]
Length: 1, dtype: physipy[m]


In [7]:
([1, 2, 3]*m).value

array([1, 2, 3])

AttributeError: module 'numpy' has no attribute 'values'

In [3]:

try:
    d = pd.Series(np.arange(10)*m,
              dtype=QuantityDtype(s))
except Exception as e:
    print('OK', str(e))
    
try:
    f = pd.Series(np.arange(10), dtype=QuantityDtype(m))
except Exception as e:
    print('OK', str(e))
    
try:
    f = pd.Series(np.arange(10)*m, dtype=QuantityDtype(1))
except Exception as e:
    print('OK', str(e))


QDTYPE : new with 1 s of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[s] with .unit 1 s
trying from sequence  [<Quantity : [0 1 2 3 4 5 6 7 8 9] m>] 10
ENTERING QARRAY with [0 1 2 3 4 5 6 7 8 9] m physipy[s] False
QARRAY : init with [0 1 2 3 4 5 6 7 8 9] m of type <class 'physipy.quantity.quantity.Quantity'>
data is set to [0 1 2 3 4 5 6 7 8 9] m with len 10 10
len values 10
OK Dimension error : dimensions of operands are T and L, and are differents.
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
OK object of type 'numpy.int64' has no len()
QDTYPE : new with 1 of type <class 'int'>
OK 


## Creation of QArray

In [14]:
qarr = np.arange(10)*m

pdqarr = QuantityArray(qarr)
e = pd.Series(QuantityArray.from_1darray_quantity(np.arange(10)*m))

QARRAY : init with [0 1 2 3 4 5 6 7 8 9] m of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [0 1 2 3 4 5 6 7 8 9] m with len 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m


<QuantityArray>
[0 m, 1 m, 2 m, 3 m, 4 m, 5 m, 6 m, 7 m, 8 m, 9 m]
Length: 10, dtype: physipy[m]

# This works

# Checking the QuantityArray constructions

In [14]:
import physipy
from physipy import m, s, DimensionError

import numpy as np
import pandas as pd

from physipandas import QuantityDtype, QuantityArray

a = pd.Series(QuantityArray(np.arange(10)*m))
b = pd.Series(QuantityArray(np.arange(10)*m))
c = pd.Series(QuantityArray(np.arange(10)*s))

print(a, b, c)

print(len(a), len(b), len(c))
print(a.shape, b.shape, c.shape)
print(type(a))
print(a.dtype)
print(type(a[0]))
print(a[0].dtype)

QARRAY : init with [0 1 2 3 4 5 6 7 8 9] m of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [0 1 2 3 4 5 6 7 8 9] m with len 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
QARRAY : init with [0 1 2 3 4 5 6 7 8 9] m of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [0 1 2 3 4 5 6 7 8 9] m with len 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
QARRAY : init with [0 1 2 3 4 5 6 7 8 9] s of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [0 1 2 3 4 5 6 7 8 9] s with len 10
QDTYPE : new with 1 s of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[s] with .unit 1 s
0   0
1   1
2   2
3   3
4   4
5   5
6   6
7   7
8   8
9   9
dtype: physipy[m] 0   0
1   1
2   2
3   3
4   4
5   5
6   6
7   7
8   8
9   9
dtype: physipy[m] 0   0
1   1
2

In [15]:
try:
    a+1
except DimensionError:
    print("OK")

print(a+1*m)
print(a+np.arange(10)*m)
print(a+a)
print(2*a)
print(a*2)
print(a**2)
print(a[0])
print(a[0:2])
print(a.iloc[0:3])

OK
QARRAY : init with [ 1  2  3  4  5  6  7  8  9 10] m of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [ 1  2  3  4  5  6  7  8  9 10] m with len 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
dtype: physipy[m]
QARRAY : init with [ 0  2  4  6  8 10 12 14 16 18] m of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [ 0  2  4  6  8 10 12 14 16 18] m with len 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
0    0
1    2
2    4
3    6
4    8
5   10
6   12
7   14
8   16
9   18
dtype: physipy[m]
QARRAY : init with [ 0  2  4  6  8 10 12 14 16 18] m of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [ 0  2  4  6  8 10 12 14 16 18] m with len 10
QDTYPE : new with 1 m of type <class 'phys

# Dataframes

In [16]:
df = pd.DataFrame({"a":a, "b":b, "c":c})

res = 2*df["a"]
df["d"] = res

df["e"] = df["d"]*2
df["g"] = df["e"]*df["a"]/df["c"]**2

QARRAY : init with [ 0  2  4  6  8 10 12 14 16 18] m of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [ 0  2  4  6  8 10 12 14 16 18] m with len 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
into copy
data is  [ 0  2  4  6  8 10 12 14 16 18] m
dtype is physipy[m]
QARRAY : init with [ 0  2  4  6  8 10 12 14 16 18] m of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [ 0  2  4  6  8 10 12 14 16 18] m with len 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
QARRAY : init with [ 0  4  8 12 16 20 24 28 32 36] m of type <class 'physipy.quantity.quantity.Quantity'>
QARRAY : init quantified values  [ 0  4  8 12 16 20 24 28 32 36] m with len 10
QDTYPE : new with 1 m of type <class 'physipy.quantity.quantity.Quantity'>
returning  physipy[m] with .unit 1 m
into copy
data is  [ 0  4  8 12 16 2

/Users/mocquin/MYLIB10/MODULES/physipy/physipy/quantity/quantity.py:189: RuntimeWarning: invalid value encountered in true_divide
  return type(self)(self.value / y.value,


In [23]:
print(df["g"].physipy.dimension)
df["g"].physipy._SI_unitary_quantity

L**2/T**2


<Quantity : 1 m**2/s**2, symbol=m**2/s**2>

In [19]:
df.physipy.to_base_units()

AttributeError: 'PhysipySeriesAccessor' object has no attribute 'to_base_units'

# This works : should fail and does

In [9]:
try:
    a=pd.Series(np.arange(10)*m,
            dtype=QuantityDtype(s))
    print("--")
    print(type(a[0]))
    print((a[0]))
except DimensionError as e:
    print(e)
    print("OK : trying to set second to m")

New dtype with :1 s
unit is 1 s <class 'physipy.quantity.quantity.Quantity'>
Constructing QuantityArray with  [<Quantity : [0 1 2 3 4 5 6 7 8 9] m>] dtype= physipy[s]
New dtype with :1 
unit is 1 <class 'physipy.quantity.quantity.Quantity'>
--
in getitiem
<class 'physipy.quantity.quantity.Quantity'>
in getitiem
[0 1 2 3 4 5 6 7 8 9]


# This fails : should be 0 m

In [10]:
a = pd.Series(np.arange(10)*m,
            dtype=QuantityDtype())
print(a[0])

New dtype with :None
unit is 1 <class 'physipy.quantity.quantity.Quantity'>
Constructing QuantityArray with  [<Quantity : [0 1 2 3 4 5 6 7 8 9] m>] dtype= physipy[]
New dtype with :1 
unit is 1 <class 'physipy.quantity.quantity.Quantity'>
in getitiem
[0 1 2 3 4 5 6 7 8 9]


# Should this work ?

In [11]:
a=pd.Series(np.arange(10), 
            dtype=QuantityDtype(s))
print(type(a[0]))
print(a[0])
print(a.values.dimension)

New dtype with :1 s
unit is 1 s <class 'physipy.quantity.quantity.Quantity'>
Constructing QuantityArray with  [0 1 2 3 4 5 6 7 8 9] dtype= physipy[s]
New dtype with :1 
unit is 1 <class 'physipy.quantity.quantity.Quantity'>
in getitiem
<class 'physipy.quantity.quantity.Quantity'>
in getitiem
0
no-dimension


In [12]:
a=pd.Series(np.arange(10)*m)
print(type(a[0]))
print((a[0]))
print(a)

<class 'physipy.quantity.quantity.Quantity'>
[0 1 2 3 4 5 6 7 8 9] m
0    [0 m, 1 m, 2 m, 3 m, 4 m, 5 m, 6 m, 7 m, 8 m, ...
dtype: object


In [13]:
s = pd.Series(["a", "b", "c", "a"], dtype="category")
s

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): ['a', 'b', 'c']

In [16]:
pd.Series(["a", "b", "c", "a"])

0    a
1    b
2    c
3    a
dtype: object

In [11]:
from pandas.api.extensions import register_extension_dtype

register_extension_dtype?

Signature: register_extension_dtype(cls: Type[pandas.core.dtypes.base.ExtensionDtype]) -> Type[pandas.core.dtypes.base.ExtensionDtype]
Docstring:
Register an ExtensionType with pandas as class decorator.

.. versionadded:: 0.24.0

This enables operations like ``.astype(name)`` for the name
of the ExtensionDtype.

Returns
-------
callable
    A class decorator.

Examples
--------
>>> from pandas.api.extensions import register_extension_dtype
>>> from pandas.api.extensions import ExtensionDtype
>>> @register_extension_dtype
... class MyExtensionDtype(ExtensionDtype):
...     name = "myextension"
File:      /opt/anaconda3/lib/python3.8/site-packages/pandas/core/dtypes/base.py
Type:      function
